### ISSUE TITLE
CF VLESS Address

### ISSUE THREAD

**Issue by WireKing** [majidrezarahnavard/way_of_freedom#12]
سلام؛ من بعضی از وب‌سایت‌هایی که پشت کلادفلر هستن رو توی این لینک جمع کردم که دوستان در انتخاب آدرس برای کانفیگ‌های ساخته شده روی ورکر کلادفلر آزادی عمل بیشتری داشته باشن:

**دوتا ویژگی عمده دارن لینک‌ها:**
**اول.** از منابع خیلی مشهور در اینترنت هستند.
**دوم.** برخی از این آدرس‌ها سرویس‌های ایرانی هستند.

امیدوارم به درد بخوره.

Link: https://webcf.xericsusi.workers.dev/

**Comment by sarinaesmailzadeh** [comment]
ممنون اضافه کردم
