### ISSUE TITLE
ublock

### ISSUE THREAD

**Issue by maanimis** [majidrezarahnavard/way_of_freedom#16]
درود بنظرتون ایرادی نداره یه توضیحی هم راجب اد بلاکرها گفته بشه؟
چون تبلیغات مصرف قابل توجهی رو دیتای اینترنت میگیرن و پهنای باند هم اشغال میکنن میتونیم همچین مطالبی رو هم اضافه کنیم؟

**Comment by meta-syfu** [comment]
ایده خوبیه

**Comment by sarinaesmailzadeh** [comment]
اوکیه. PR بزنید.
