### ISSUE TITLE
اضافه کردن پروانه نشر

### ISSUE THREAD

**Issue by ahangarha** [majidrezarahnavard/way_of_freedom#8]
با استفاده از یک پروانه نشر آزاد مناسب آثار فرهنگی، امکان مشارکت، بازنشر و مشارکت مؤثرتر را فراهم آورید. 

می‌توانید محتوا را با پروانه‌هایی مثل CC0 یا حتی Public Domain در مالکیت عمومی قرار دهید.

**Comment by sarinaesmailzadeh** [comment]
ممنون اضافه کردم
